### ISSUE TITLE
A python error when opening the app

### ISSUE THREAD

**Issue by ashraf2033** [zack-ashen/keep-cli#3]
`Traceback (most recent call last):
  File "/home/xxxxxxxxx/.local/bin/keep-cli", line 5, in <module>
    from keep.keep import main
  File "/home/xxxxxxxxx/.local/lib/python3.10/site-packages/keep/keep.py", line 19, in <module>
    from PyInquirer import prompt
  File "/home/xxxxxxxxx/.local/lib/python3.10/site-packages/PyInquirer/__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "/home/xxxxxxxxx/.local/lib/python3.10/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/home/xxxxxxxxx/.local/lib/python3.10/site-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/home/xxxxxxxxx/.local/lib/python3.10/site-packages/prompt_toolkit/application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "/home/xxxxxxxxx/.local/lib/python3.10/site-packages/prompt_toolkit/key_binding/bindings/basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "/home/xxxxxxxxx/.local/lib/python3.10/site-packages/prompt_toolkit/renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "/home/xxxxxxxxx/.local/lib/python3.10/site-packages/prompt_toolkit/styles/__init__.py", line 8, in <module>
    from .from_dict import *
  File "/home/xxxxxxxxx/.local/lib/python3.10/site-packages/prompt_toolkit/styles/from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
`

**Comment by wdog** [comment]
# ERROR

```python
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

# FIX

edit the file `~/.local/lib/python3.10/site-packages/prompt_toolkit/styles/from_dict.py`

change

```python
# from collections import Mapping
from collections.abc import Mapping
```
